name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
           xcodebuild clean build -target "Triangle.xcodeproj" -scheme "Triangle" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run tests
      run: |
           xcodebuild clean test  -target "Triangle.xcodeproj" -scheme "Triangle" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" -enableCodeCoverage "YES" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
